### ISSUE TITLE
Application Server does not run.

### ISSUE THREAD

**Issue by muratcanberber** [svelte-view-engine/sve-app#5]
// git clone https://github.com/user896724/sve-app is wrong because the username was changed.
https://github.com/svelte-view-engine/sve-app
cd sve-app
npm i
npm start # listens on localhost:3000

`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'flowfs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mcb/Desktop/Projects/sve-app-master/sve-app/node_modules/svelte-view-engine/src/Engine.js:2:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sve-app@2.0.0 start: `node src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sve-app@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by ptkdev** [comment]
Solution: `npm install flowfs --save` but app crash again with:

```
Error: Cannot find module 'svelte/package.json'
Require stack:
```

**Comment by Donny-H** [comment]
> Solution: `npm install flowfs --save` but app crash again with:
> 
> ```
> Error: Cannot find module 'svelte/package.json'
> Require stack:
> ```

Any solutions? I tried an npm update but just get a different error:

`Cannot find module 'svelte/compiler`
